# Generated by Django 4.1.7 on 2023-11-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdb',
            name='Description',
            field=models.CharField(default='desc', max_length=500),
            preserve_default=False,
        ),
    ]
